name: Keep-Alive-Ping

on:
  schedule:
    - cron: '*/5 * * * *' # Pings every 5 minutes instead of 14
  workflow_dispatch:      # Allows you to click a button to test it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: curl -s "https://coast-d9he.onrender.com"
